POST http://localhost:3000/highlight HTTP/1.1
content-type: text/html

<pre class="language-csharp"><code>public class HelloWorld { public static void Main() { System.Console.WriteLine("Hello, World!"); } }</code></pre>
